dataware-tools/app-data-browser-next

- .github/workflows/build_and_deploy.yml
- .github/workflows/build_and_test.yml
Use GitHub-hosted runners for CI
Public repositories can use unlimited runners
> Use GitHub-hosted runners

- src/components/molecules/DatabaseMenuButton.tsx
レコード一覧ページ，ヘッダーのオプションまとめたアイコンを3本線ではなく水平に3つの点が並んだアイコンに変更
- More的なアイコンはこちらのほうが一般的と思われる
- GitHubを参考にしてます
- Issue: https://github.com/dataware-tools/dataware-tools/issues/32
> Change more icon to MoreHoriz

- src/globalStates.ts
atomのキーで被っていたものがあったため変更
以下の警告が出ていた
```
Duplicate atom key "recordPaginateState". This is a FATAL ERROR in
production. But it is safe to ignore this warning if it occurred because of
hot module replacement.
```
> Fix duplicated atom key

- src/components/organisms/InputConfigList.tsx
- src/components/organisms/OptionSharingSelects.tsx
一部のフォームに垂直方向のパディングを追加
モーダルウィンドウのフォームで上が見切れる問題を解決
Issue: https://github.com/dataware-tools/dataware-tools/issues/49
> Fix bug of modal form cut out

- package-lock.json
- package.json
- src/components/organisms/DatabaseList.tsx
- src/components/organisms/RecordList.tsx
- Replace Table of dataware-tools to DataGrid of material-ui
- DataGrid have some function helping improvement of data showing page
Resolves https://github.com/dataware-tools/dataware-tools/issues/29
> Replace Table of dataware-tools to DataGrid of material-ui

- package-lock.json
- package.json
- src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
This patch includes the following updates:
- Bump eslint-plugin-compat from 3.9.0 to 3.11.1 #104
- Bump eslint-config-standard from 16.0.2 to 16.0.3 #103
- Bump eslint-plugin-react from 7.23.2 to 7.24.0 #100
- Bump react-dom from 17.0.1 to 17.0.2 #98
- Bump @testing-library/user-event from 13.1.5 to 13.2.1 #97
To update dependencies
> Bump dependencies

- src/utils/index.ts
- Add initial config
- For easy starting to use database
- Resolves https://github.com/dataware-tools/dataware-tools/issues/40
> Add initial config for easy starting to use database

- package-lock.json
- package.json
- src/components/organisms/DatabaseList.tsx
- src/components/organisms/FileList.tsx
- src/components/organisms/RecordList.tsx
app-common をアップデートし各種削除時の確認モーダルで削除用のスタイルを設定
- データベース削除
- レコード削除
- ファイル削除
削除確認モーダルのスタイルをわかりやすくしたい
- Issue: https://github.com/dataware-tools/dataware-tools/issues/27
- app-common PR: https://github.com/dataware-tools/app-common/pull/86
> Apply delete mode for confirm modal on deleting

- package-lock.json
- package.json
- src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
- src/components/organisms/DatabaseEditModal.tsx
- src/components/organisms/DatabaseList.tsx
- src/components/organisms/DisplayConfigEditModal.tsx
- src/components/organisms/ExportMetadataModal.tsx
- src/components/organisms/FileEditModal.tsx
- src/components/organisms/FileList.tsx
- src/components/organisms/InputConfigEditModal.tsx
- src/components/organisms/RecordDetailModal.tsx
- src/components/organisms/RecordEditModal.tsx
- src/components/organisms/RecordInfo.tsx
- src/components/organisms/RecordList.tsx
- src/components/organisms/SearchConfigEditModal.tsx
- src/components/organisms/SecretConfigEditModal.tsx
- src/components/pages/DatabasesPage.tsx
- src/components/pages/RecordsPage.tsx
- src/utils/index.ts
- Show easy understood message when [server error responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses) is returned
- Stop showing "Please reload this page" when fetch error occur
- To improve usability 
- The message have no mean, and sometimes lead misunderstanding
- Related https://github.com/dataware-tools/dataware-tools/issues/63
- Depends on https://github.com/dataware-tools/app-common/pull/85
> Show easy understood message when fetch error occur

- src/components/molecules/Sample.tsx
- Rewrite Sample component by new coding style
- 今のコーディングスタイルでは幾つか不便な点があったから
- **`TypeError: "x" has no properties ` といったエラーが起きた場合には，スタックトレースに表示されるコンポーネント名が `Component$3` や `Container$7` 等になるため，どこでバグが起きているのか追いづらかった**
- **ロジックコンポーネントで `useStyles` を使っているので，Storybook でビュー側だけを利用しようとした場合に面倒が多かった**
- **ロジックコンポーネントで `useStyles` を使っているので，特にロジックがなくてもスタイルが付くだけでロジックコンポーネントを用意しなくてはならなかった**
- IDE 等で定義に飛んだ結果，カーソルが当たる部分が `Container` になるため，初見で理解しづらかった
- 分割代入の記法と関数コンポーネントの記法に習熟していないと入力と出力の型を追いづらかった
- 現状感じているこの書き方の辛い点
- ロジック側でビューの props の型を参照するときに，今までは `Props["hoge"]` で済んでいたのが，`SomeNameDOMProps["hoge"]` となり，多少面倒
- ビューコンポーネントが `useStyles` を含むので，Material-UI から離れる時にビューコンポーネントをそのままは流用出来ない
> Rewrite Sample component by new coding style

- src/components/pages/RecordsPage.tsx
Fix bugs that pagination parameter remain when moving between databases
Bug fix
↓ がバグの様子
> Fix bugs that pagination parameter remain when moving between databases

- src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
- src/components/molecules/FilePreviewer/index.tsx
- src/components/organisms/FileDownloadUrlInjector.tsx
Add feature to open a rosbag file directly by streaming from api-file-provider.
Some rosbag files do not require additional ROS-nodes to preview the file.  
In that case, streaming data directly from the file improves user experience.
https://user-images.githubusercontent.com/24401842/140878120-37cb3c3e-256a-480a-8947-63cea21e6ecd.mov
> Support previewing rosbag files without rosbridge

- src/components/organisms/InputConfigList.tsx
Fix to add new clumn to last of input config
To imporove UX
Before
After
> Fix to add new clumn to last of input config

- package-lock.json
- package.json
- src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
- src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
- src/components/molecules/FilePreviewer/index.tsx
- src/components/organisms/FileList.tsx
- src/components/organisms/FilePreviewModal.tsx
Support for job-type `ros-provider-with-pydtk`
To use app-scene-viewer
https://github.com/dataware-tools/api-job-store/pull/26
https://github.com/dataware-tools/protocols/pull/52
https://user-images.githubusercontent.com/24401842/145756976-be0fce9c-be0c-4e56-a170-9fcf7f71be69.mov
> Support for job-type `ros-provider-with-pydtk`

- package.json
- src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
- src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
- src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
- src/utils/fetchClients.tsx
- src/utils/utilTypes.ts
Support for the latest API-specifications of api-job-store
To enable permission check of api-job-store
https://github.com/dataware-tools/protocols/pull/53
https://github.com/dataware-tools/api-job-store/pull/27
https://www.notion.so/humandatawarelab/api-job-store-permission-check-44e6a95bfdde4448b13624c73b79bcbb
https://user-images.githubusercontent.com/24401842/146141370-1175bc05-cb9b-49a5-80dc-bd512f1d4208.mov
> Support for api-job-store with database-id

- .github/dependabot.yml
Fix "Dependabot can't authenticate to a private package registry" error
dependabot にちゃんと動いてほしいので
[Docs for troubleshooting dependabot error](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/troubleshooting-dependabot-errors#dependabot-cant-resolve-or-access-your-dependencies)
[Docs for dependabot config](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#npm-registry)
> Fix "Dependabot can't authenticate to a private package registry" error

- .github/dependabot.yml
Bug fix on dependabot config
```The property '#/registries' includes the "npm-github" registry which is not used in any of the configurations```
と怒られたので
> Bug fix on dependabot config

- .storybook/main.js
- tsconfig.json
- vite.config.ts
Fix build config for symlinking app common
app-common をシンボリックリンクしたときに，コンポーネントの見た目が違うものになっていて，ヴィジュアルリグレッションテストが正しく行えないから
原因は，app-common の peerDependencies に含まれるライブラリが重複し，MUI の theme が反映されなくなることにあると思われる
- 修正前
- 修正後
> Fix build config for symlinking app common

- package.json
Bump app-common to v21.12.10
To update
https://github.com/dataware-tools/app-common/pull/144
> Bump app-common to 21.12.10

- src/pages/RecordsPage.tsx
Show menu button even if database have error
Database should be able to be deleted even if it have error
Resolves https://github.com/dataware-tools/dataware-tools/issues/115
> Show menu button even if database have error

- src/components/organisms/ExportMetadataModal.tsx
メタ情報のエクスポート機能で以下の点を修正:
- csvでの出力時に無駄に `"` で囲われる問題を修正
- カラム名が display_name に変換されていなかった問題を修正
- ファイルパスに `/` など不要なものが含まれていた問題を修正
バグ修正のため
> Fix the feature of downloading metadata

- src/App.tsx
- src/components/organisms/DatabaseEditModal.tsx
- src/utils/index.ts
- src/utils/toasts.tsx
- app-commonのToasterコンポーネントとToastHavingDetailInfoコンポーネントをエラーのフィードバックとして使うようにした
- ひとまずデータベース追加・更新時に対応
ある操作に対する一時的なエラーをトーストに切り替えたい
PR on app-common: https://github.com/dataware-tools/app-common/pull/258
https://user-images.githubusercontent.com/13210107/181449193-1e40829f-1227-46b6-8b76-a3bcd829863c.mov
> Use toast for visualizing error on database add and update

- src/components/organisms/DatabaseEditModal.tsx
- Fix bug that database is deleted when database having same id is tended to be added
- Do not delete database when occur error relating adding database
Bug fixes
https://user-images.githubusercontent.com/72174933/181734840-5aa37e3b-a703-45ea-aba8-4a52c2724a64.mov
> Fix bug that database is deleted when database having same id is tended to be added

- src/components/organisms/DatabaseConfigModal/index.tsx
- src/components/organisms/DatabaseDeleteModal.tsx
- src/components/organisms/FileEditModal.tsx
- src/components/organisms/FileList.tsx
- src/components/organisms/MetadataEditModal.tsx
- src/components/organisms/RecordDetailModal.tsx
- src/components/organisms/RecordEditModal.tsx
- src/components/organisms/RecordList.tsx
各アクションの失敗時のエラーを通知をトーストに置き換える
ユーザーの操作に対する一時的なエラーをトーストに切り替えたい
Issue: https://github.com/dataware-tools/dataware-tools/issues/68
Related PR: #483
> Use toast for error notification
