dataware-tools/app-data-browser-next

src/components/organisms/DisplayConfigEditModal.tsx, src/components/organisms/ExportMetadataModal.tsx, src/components/organisms/InputConfigAddModal.tsx, src/components/organisms/InputConfigEditModal.tsx, src/components/organisms/RecordEditModal.tsx, src/components/organisms/RecordList.tsx, src/components/organisms/SearchConfigEditModal.tsx, src/components/organisms/SecretConfigEditModal.tsx
- Fix bug that error remain in modal some times
- Bug fixes
=> Fix bug that error remain in modal some times

src/components/pages/DatabasesPage.tsx, src/components/pages/RecordsPage.tsx
- Show config modal after creating database
- Showing confusing error cause bad UX
- https://github.com/dataware-tools/dataware-tools/issues/30
=> Show config modal after creating database

src/components/organisms/FileEditModal.tsx, src/components/organisms/FileList.tsx, src/components/organisms/InputConfigEditModal.tsx, src/components/organisms/MetadataEditModal.tsx, src/components/organisms/RecordEditModal.tsx, src/utils/fetchClients.tsx, src/utils/index.ts, src/utils/utilTypes.ts
- Support editing file metadata
- Edit file metadata on Web GUI
- https://github.com/dataware-tools/dataware-tools/issues/18
=> Support editing file metadata

src/components/organisms/DatabaseAddModal.tsx, src/components/organisms/DisplayConfigEditModal.tsx, src/components/organisms/ExportMetadataModal.tsx, src/components/organisms/FileEditModal.tsx, src/components/organisms/InputConfigEditModal.tsx, src/components/organisms/RecordEditModal.tsx, src/components/organisms/RecordList.tsx, src/components/organisms/SearchConfigEditModal.tsx, src/components/organisms/SecretConfigEditModal.tsx, src/components/pages/RecordsPage.tsx, src/utils/index.ts
- Show easy understood error
- Make understanding error easy
https://github.com/dataware-tools/dataware-tools/issues/22
=> Show easy understood error

src/pages/_app.tsx, src/pages/_document.tsx
- Show favicon
- Fix tab name
- bug fix 
- Resolves https://github.com/dataware-tools/dataware-tools/issues/48
=> Fix appearance of browser tab

src/components/organisms/ExportMetadataModal.tsx, src/components/organisms/FileList.tsx, src/components/organisms/MetadataEditModal.tsx, src/components/organisms/RecordDetailModal.tsx
- Replace built-in confirming function to ours
- Show modal designed by us when confirming user's action
- Resolves https://github.com/dataware-tools/dataware-tools/issues/9
=> Replace built-in confirming function to ours

src/components/organisms/DatabaseAddModal.tsx
データベース追加フォームにマージン追加
一目でグループがわかるようにしたい
Issue: https://github.com/dataware-tools/dataware-tools/issues/31
=> Add margin to add database modal

src/components/molecules/FilePreviewer/DefaultPreviewer.stories.tsx, src/components/molecules/FilePreviewer/DefaultPreviewer.tsx, src/components/molecules/FilePreviewer/FilePreviewer.stories.tsx, src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx, src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx, src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx, src/components/molecules/FilePreviewer/RosbagPreviewer/RosbagPreviewer.stories.tsx, src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx, src/components/molecules/FilePreviewer/TextPreviewer.stories.tsx, src/components/molecules/FilePreviewer/TextPreviewer.tsx, src/components/molecules/FilePreviewer/VideoPreviewer.stories.tsx, src/components/molecules/FilePreviewer/VideoPreviewer.tsx, src/components/molecules/FilePreviewer/index.tsx, src/components/molecules/FilePreviewer/types.ts, src/components/molecules/SoloSelect.tsx, src/components/organisms/FilePreviewModal.tsx, src/utils/fetchClients.tsx
- Support previewing rosbag file
- Preview rosbag file by Web GUI
- Resolves https://github.com/dataware-tools/dataware-tools/issues/1
- Related https://github.com/dataware-tools/dataware-tools/issues/47
=> Support previewing rosbag file

package-lock.json, package.json, src/components/organisms/DatabaseList.tsx
- Make scrollablity of database list clear
- Improve UX
Resolves https://github.com/dataware-tools/dataware-tools/issues/28
=> Make scrollablity of database list clear

package-lock.json, package.json, src/components/organisms/RecordDetailModal.tsx, src/components/organisms/RecordInfo.tsx
- Fix bug that too long content have unexpected appearance
- bug fix
- Resolves https://github.com/dataware-tools/dataware-tools/issues/43
=> Fix bug that too long content have unexpected appearance

src/components/organisms/DatabaseAddModal.tsx, src/components/organisms/InputConfigList.tsx, src/components/organisms/RecordDetailModal.tsx, src/utils/index.ts
- Add system metadata to created file
- 便利だから
- Resolves https://github.com/dataware-tools/dataware-tools/issues/38
=> Add system metadata to created file

src/components/organisms/DatabaseList.tsx
- Support deletting database
- Fix bug https://github.com/dataware-tools/dataware-tools/issues/58#issuecomment-886448525
- Delete database from WebGUI
- Resolves https://github.com/dataware-tools/dataware-tools/issues/55 https://github.com/dataware-tools/dataware-tools/issues/58#issuecomment-886448525
=> Support deletting database

package-lock.json, src/components/organisms/RecordList.tsx, src/components/pages/RecordsPage.tsx, src/globalStates.ts
- Support sorting record list
- 各カラムでソートしたいから
- Resolves https://github.com/dataware-tools/dataware-tools/issues/37
=> Support sorting record list

src/components/organisms/RecordDetailModal.tsx, src/utils/fetchClients.tsx
- Fix bug that duplicated file error does not occur
- Bug fix
- Resolves https://github.com/dataware-tools/dataware-tools/issues/62
=> Fix bug that duplicated file error does not occur

src/components/molecules/DatabaseMenu.tsx, src/components/molecules/FilePreviewer/AudioPreviewer.tsx, src/components/molecules/Sample.tsx, src/components/molecules/SoloSelect.tsx, src/components/organisms/ExportMetadataModal.tsx, src/components/organisms/InputConfigAddModal.tsx
- Fix import path
- To avoid bundle useless modules
- https://next.material-ui.com/guides/minimizing-bundle-size/#development-environment
=> Fix import path

src/components/organisms/FileList.tsx, src/components/organisms/FileListItem.tsx, src/components/organisms/FilePreviewModal.tsx, src/utils/fetchClients.tsx, src/utils/index.ts
- Add button for viewing neighbor file in file previewing dialog
- To improve UX
- Resolves https://github.com/dataware-tools/dataware-tools/issues/46
=> Add button for viewing neighbor file in file previewing dialog

src/components/pages/DatabasesPage.tsx, src/components/pages/RecordsPage.tsx
- Fix bug that query parameter and pagination state are not sync
- Bug fix
=> Fix bug that query parameter and pagination state are not sync

.github/workflows/auto-merge.yml, .github/workflows/build_and_deploy.yml, .github/workflows/build_and_test.yml, Dockerfile
- Add workflow to automate merging PR created by dependabot
- パッチバージョンは自動でアップデートしたいから
=> Add workflow to automate merging PR created by dependabot

.github/workflows/codeql-analysis.yml
- Test codeql-analysis
- 試したいので
=> Test codeql-analysis

package-lock.json, package.json, src/components/organisms/DatabaseDeleteModal.tsx, src/components/organisms/RecordListMapView.stories.tsx, src/components/organisms/RecordListMapView.tsx, src/components/pages/RecordsPage.tsx
Support showing record list as marker on map
便利なので
=> Support showing record list as marker on map

src/components/organisms/RecordInfo.tsx
Collapse raw json view
To display raw json as possible as fasyly
Resolves https://github.com/dataware-tools/dataware-tools/issues/95
=> Collapse raw json view

src/components/molecules/FilePreviewer/CsvPreviewer.tsx, src/components/molecules/FilePreviewer/TextPreviewer.stories.tsx, src/components/molecules/FilePreviewer/VideoPreviewer.stories.tsx, src/components/molecules/OptionSharingSelectsItem.tsx, src/components/organisms/ControlledDatabaseMenuButton.tsx, src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.tsx, src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.tsx, src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.tsx, src/components/organisms/DatabaseConfigModal/index.tsx, src/components/organisms/DatabaseDeleteModal.tsx, src/components/organisms/DatabaseEditModal.tsx, src/components/organisms/DatabaseList.tsx, src/components/organisms/ExportMetadataModal.tsx, src/components/organisms/FilePreviewModal.stories.tsx, src/components/organisms/MetadataEditModal.tsx, src/components/organisms/RecordList.tsx
Run auto formatting of prettier
prettier のバージョンが上がってフォーマットが変わったから
=> Run auto formatting of prettier

src/components/molecules/Sample.tsx, src/utils/index.ts
Fix swr usage as recommended in docs
swr が v1 になって API が変わって，推奨される使用法も変わったから
https://swr.vercel.app/blog/swr-v1#migration-guide
=> Fix usage of swr

.storybook/preview.js, package-lock.json, package.json, src/Router.tsx, src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx, src/components/organisms/DatabaseDeleteModal.tsx, src/components/organisms/DatabaseList.tsx, src/pages/DatabasesPage.tsx, src/pages/IndexPage.tsx, src/pages/RecordsPage.tsx
Bump react-router-dom
メジャーバージョンのアップデートでAPIが変わったので
https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6
=> Bump react-router-dom

src/components/organisms/MetadataEditModal.tsx
Fix bug that Number and Datetime can't be changed to empty 
Bug fixes
Resolves https://github.com/dataware-tools/dataware-tools/issues/112
=> Fix bug that Number and Datetime can't be changed to empty 

package-lock.json, package.json, src/components/organisms/DatabaseConfigModal/index.tsx, src/components/organisms/DatabaseEditModal.tsx, src/components/organisms/MetadataEditModal.tsx
Confirm trashing changed data
簡単な操作ミスのせいで頑張って編集したデータが一瞬で消えると，大きなストレスになるので
Related: https://github.com/dataware-tools/dataware-tools/issues/104
=> Confirm trashing changed data

src/components/organisms/RecordInfo.tsx
Fix bugs that "copy to clip board" not works
Bug fixes
Resolves https://github.com/dataware-tools/dataware-tools/issues/102
=> Fix bugs that "copy to clip board" not works

src/components/organisms/FileList.tsx, src/components/organisms/RecordList.tsx
Show deleted target name
削除する対象を分かりやすくするため
Related https://github.com/dataware-tools/dataware-tools/issues/114
=> Show deleted target name

package-lock.json, package.json, src/components/organisms/DatabaseConfigModal/index.tsx, src/components/organisms/DatabaseEditModal.tsx, src/components/organisms/MetadataEditModal.tsx
Confirm closing window when changed data exists
誤操作で変更中のデータが吹っ飛ぶのを防ぎたいから
Related : https://github.com/dataware-tools/dataware-tools/issues/117
See https://github.com/dataware-tools/app-common/pull/208
=> Confirm closing window when changed data exists

package-lock.json, package.json
Bump serve to v14
Bump dependencies
=> Bump serve to v14
